chain:
  bech32_prefix: desmos
  modules:
    - profiles
    - subspaces
    - posts
    - reactions

node:
  type: remote
  config:
    rpc:
      client_name: athena
      address: https://rpc.mainnet.desmos.network:443
      max_connection: 10

    grpc:
      address: https://grpc.mainnet.desmos.network:443
      insecure: false

parsing:
  workers: 1
  listen_new_blocks: true
  parse_old_blocks: true
  start_height: 13219150

database: 
  url: postgres://athena_user:athena_password@postgres:5432/athena_db?sslmode=disable

logging:
  level: debug
  format: text

contracts:
  tips:
    code_id: 11

filters:
  supported_subspace_ids: [21]